name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Android APK di Cloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Siapkan Capacitor & Project Android
        run: |
          npm init -y
          npm install @capacitor/core @capacitor/cli @capacitor/android
          npx cap init "Kelas 8A" "com.sekolah.kelas8a" --web-dir "."
          npx cap add android

      - name: Compile APK Menggunakan Gradle
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleDebug --no-daemon

      - name: Unggah Hasil File APK
        uses: actions/upload-artifact@v4
        with:
          name: Kelas-8A-Android-App
          path: android/app/build/outputs/apk/debug/app-debug.apk
